services:
  #-----------------
  # NextCloud image
  #-----------------
  nextcloud:
    image: kefaslungu/hng-nextcloud
    container_name: nextcloud
    restart: always
    networks:
      - detector-net
    volumes:
      - HNG-nginx-logs:/var/log/nginx:ro

  #----------------
  # Nginx image
  #-----------------
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    networks:
      - detector-net
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - HNG-nginx-logs:/var/log/nginx

  detector:
    build: ./detector
    privileged: true
    container_name: detector
    restart: always
    networks:
      - detector-net
    volumes:
      - HNG-nginx-logs:/var/log/nginx:ro
      - detector-audit-logs:/var/log/detector
      - /var/lib/anomaly:/app/shared
    environment:
      WEB_HOOK_URL: ${WEB_HOOK_URL}


#----------------
# Volumes
#----------------
volumes:
  HNG-nginx-logs:
  detector-audit-logs:

#--------------------
# Internal Network
#--------------------
networks:
  detector-net:
    driver: bridge
