log:
  path: /var/log/nginx/hng-access.log

slack:
  webhook_url: ${WEB_HOOK_URL}

thresholds:
  z_score_max: 3.0
  spike_multiplier: 5.0
  error_multiplier: 3.0
  window_size: 60

blocker:
  ban_duration:
    - 600
    - 1800
    - 7200
    - -1
  iptables_chain: DOCKER-USER

dashboard:
  host: 0.0.0.0
  port: 5000

audit_log:
  path: /var/log/detector/audit.log